### PR TITLE
triangle tests now conforming to canonical

### PR DESCRIPTION
**Pull request by neenjaw**
- [x] `version` bumped to 1.2.1
- [x] trailing whitespace removed from README.md
- [x] `triangle.example` and `triangle_tests.plt`:
  - There was some inconsistencies with the triangle predicate which @Average-user pointed out in #81,
  - the tests were treating it like `triangle(+Side1, +Side2, +Side3, +Type)` but it was written in `triangle.example` to only be correct if used `triangle(+Side1, +Side2, +Side3, -Type)`
  - `triangle.example` has been changed now to pass the tests.

### CODE REVIEW

**Comment by Average-user** [comment]
@neenjaw Ok to merge?

**Comment by neenjaw** [comment]
I'm good if you're happy with it, 

I thought I fixed the trailing newline on the `version` file, but it seems to be missing.

**Comment by Average-user** [comment]
Thats because there were conflicts with master. I think I fixed them but I never understood that tool weell enough. Will see after merge

**Comment by Average-user** [comment]
But do you want it with or without a newline at end?

**Comment by neenjaw** [comment]
I like it on, because then there isn't that symbol on the diff, but I can't push a commit for 30 minutes or so until I can get to a computer

**Comment by neenjaw** [comment]
Ready!

**Pull request merged**
