### PR TITLE
Core exercises (Round1)

### PR DESCRIPTION
**Pull request by Average-user**

### CODE REVIEW

**Comment by Average-user** [comment]
Trying to get the Prolog track structured following Round 1 of  project track anatomy. This are only early steps, I presume that with following rounds this could change a lot.

**Comment by Average-user** [comment]
Current order of core exercises:

- hello-world
- queen-attack
- triangle
- isogram
- binary
- rna-transcription
- anagram
- pascals-triangle
- dominoes

**Comment by F3PiX** [comment]
@Average-user I just realized that all the side exercises are still `unlocked_by: null`, meaning that they will be presented to the student immediately after Hello World. 

To prevent this, they should be unlocked by one of the core exercises.

You probably want to add that to this PR.

**Comment by Average-user** [comment]
@F3PiX  Isn't that part of some other Round in the tool?

**Comment by F3PiX** [comment]
Usually, yes. But in case of Prolog, before this PR all the exercises were `core: false, unlocked_by: null`. (And the website randomly picked some to appear as 'core' to students.)

Since this PR introduces real core exercises (`core: true, unlocked_by: null`),  _all_  other exercise are `unlock_by: null`, meaning: unlocked after Hello World. That's the opposite from what you try to accomplish with this PR. 

I didn't realize this would be a problem before. This is the first track tested that had no real core exercises. I added the use case to the Tool, so this will be clear for next tracks in this situation.

**Comment by F3PiX** [comment]
@Average-user How about merging this step first, and open an issue for redividing the side exercises?

There's not much profit in letting this PR sit here instead of merging :-)

**Comment by Average-user** [comment]
@F3PiX Thanks for the help

**Pull request merged**
