### PR TITLE
add default version

### PR DESCRIPTION
**Pull request by neenjaw**
I'd like to get the `track maintenance tool` working for the prolog track, this adds the version metadata to a file in a `.meta` directory for each exercise with the default version of `0.0.0` which can later be bumped to the current version once the tests are validated against the `exercism/problem-specification` repo's canonical test versions.

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Nice

**Comment by Average-user** [comment]
Looks great. Should I merge?

**Comment by neenjaw** [comment]
Please :)

**Comment by SleeplessByte** [comment]
Once [this](https://github.com/exercism/tracks-maintenance-dashboard/commit/6f3b2629498aff5c58ec2494813a01b58285c719/checks?check_suite_id=260590337) is green, your versions will start showing up [here](https://tracks.exercism.io/prolog/master/versions).

**Pull request merged**
